[package]
name = "tcp_server"
version = "0.1.0"
authors = ["jiangbowen_ <18853716897@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
